### ISSUE TITLE
Empty field 'equipment' is not synchronized via OpenImmo import

### ISSUE THREAD

**Issue by jpeters78** [oliverklee/ext-realty#124]
realty 0.6.56

Which fields are synchronized?
Is there a way to define which fields should be synchronized?

**Comment by oliverklee** [comment]
The field "equipment" is import from OpenImmo: freitexte > ausstatt_besch

https://github.com/oliverklee/ext-realty/blob/master/lib/class.tx_realty_domDocumentConverter.php#L73

**Comment by jpeters78** [comment]
The initial import was done correctly. With the next import the field 'title' was updated, but not the field 'equipment'.

**Comment by jpeters78** [comment]
In the csv file the field is empty. That's probably why the field <ausstatt_besch> is missing in <immobilie> in the generated xml file (via csv_to_openimmo). And so it's not synchronized?

But the field should also be emptied in the realty object.

**Comment by oliverklee** [comment]
I'll look into it and fix it (probably in the CSV-to-OpenImmo extension).

**Comment by oliverklee** [comment]
I've just tested the import manually: With the updated CSV extension, a non-empty value for equipment can now be overwritten with an empty value. So only the update of the CSV extension is needed, not of the realty extension (as far as this bug is concerned).
