### ISSUE TITLE
activate lightbox?

### ISSUE THREAD

**Issue by dbfischer** [oliverklee/ext-realty#125]
In Single-View the pictures don't open in a lightbox
enableLightbox = 1 is activated

Other pictures in content open in a lightbox with prettyPhoto.
Website is made with css_styled_content and bootstrap.

**Comment by oliverklee** [comment]
Please post your issues in English so that persons who don't speak German can also read your issue. Thanks!

**Comment by dbfischer** [comment]
jQuery is included
only /typo3conf/ext/realty/Resources/Public/Lightbox/css/lightbox.css is included but no JavaScript.
Should is be included automatically with realty or is it necessary to include it in TS setup?
I use original template and 1.0.1.

**Comment by dbfischer** [comment]
TYPO3 7.6.31
Static TS template is included.
![screenshot-static-templates](https://user-images.githubusercontent.com/15387379/47507100-d0283480-d871-11e8-89b1-2acfcdcf1897.jpg)
TS object browser: no lightbox in
_[includeJSFooterlibs]
    [flexslider2] = EXT:bootstrap_grids/Resources/Public/Flexslider2/jq...
    [async] = 1
    [defer] = 1
    [custom] = fileadmin/bsdist/theme/js/scripts.min.js_

**Comment by dbfischer** [comment]
all entries from Page.txt are okay except of
includeJSFooterlibs {
lightbox = EXT:realty/Resources/Public/Lightbox/js/lightbox.js


In object browser I find several entries with
[override] = <figure class="image lightbox###CLASSES###">|</figure> and
[override] = <div class="image lightbox###CLASSES###">|</div>

Does it help to give you an BE login via PM?

**Comment by dbfischer** [comment]
Sorry, just found in TS:
  includeJSlibs {
    jquery = {$plugin.tx_bootstrapcore.theme.jQueryJsFile}
    gototop = {$plugin.tx_bootstrapcore.theme.baseDir}/js/gototop.js
  }
It is from the bsdist distribution.
After commenting it out, the realty lightbox works ... but then the prettyPhoto lightbox works not.

**Comment by oliverklee** [comment]
Does adding this to the TS help?
```
includeJSFooterlibs {
        realtyLightbox = EXT:realty/Resources/Public/Lightbox/js/lightbox.js
    }
```

If not, would you be willing to debug this further and provide a pull request?

**Comment by dbfischer** [comment]
Yes, this solves the problem. Thanks.
