### ISSUE TITLE
How can I restrict fields for feEditors?

### ISSUE THREAD

**Issue by dbfischer** [oliverklee/ext-realty#160]
Maybe I am to blind to see ... but I don't find a property for hiding fields (or fields to show) for feEditors, when they create a new object.

There are properties like
_fieldsInSingleViewTable_
_visibleContactFormFields_
but nothing with feEditor.

**Comment by oliverklee** [comment]
That's correct. You'll need to use a custom HTML template for this.

**Comment by dbfischer** [comment]
Thank you!
A hint in documentation to pi1/tx_realty_frontEndEditor.html can avoid questions like this. ;-)

**Comment by oliverklee** [comment]
> A hint in documentation to pi1/tx_realty_frontEndEditor.html can avoid questions like this. ;-)

Good idea! Would you be willing to create a pull request for this?
