### ISSUE TITLE
API-Key für Google Maps

### ISSUE THREAD

**Issue by ghost** [oliverklee/ext-realty#47]
Gibt es bei der realty-Extension eine Möglichkeit, den API-Key zu hinterlegen? Bei den Objekten wird die Karte leider nicht abgerufen.

**Comment by oliverklee** [comment]
@vmAKT Bisher noch nicht. Kann ich aber gerne nachrüsten. Der Aufwand wären 1,5-3 Stunden.

Da das sowohl Anpassungen an der realty als auch der oelib erfordert, empfehle ich, dass wir das erst nach dem Update auf TYPO3 7.6 in Angriff nehmen, weil die aktuelle oelib TYPO3 >= 7.6 voraussetzt. (Ansonsten müsste ich das noch bei der oelib 1.4.x nachrüsten, was zusätzlichen Aufwand bedeuten würde.)

**Comment by oliverklee** [comment]
Oh, und fürs Geocoding wäre es auch sinnvoll, dass ich da den API-Key nachrüste. Der Aufwand dafür bei der oelib und realty wären noch einmal 1-2 Stunden.

**Comment by vmAKT** [comment]
In der vorherigen Version hat es wohl mit der Kartenansicht via Google Maps geklappt. Könnten Sie auch hier bitte Kontakt mit meiner Kollegin aufnehmen? Besten Dank.

**Comment by oliverklee** [comment]
Stand der Dinge nach dem Telefonat mit Frau Peters: Sie frage mal beim Kunden nach, ob es gewünscht bzw. möglich ist, dass ein Google-API-Key zum Einsatz kommt.
