### ISSUE TITLE
No information regarding 8.7 in the manual

### ISSUE THREAD

**Issue by millemedia** [oliverklee/ext-realty#95]
Hi Oliver,

in the extension repository there is a hint thas in the manual are information about version compatibility with 8.7. I didn't found that.

Best regards

Andreas

**Comment by oliverklee** [comment]
Hi @millemedia, the corresponding information is on the TER page of the extension and on Packagist (both automatically extracted from the `ext_emconf.php` and `composer.json`):

https://extensions.typo3.org/extension/realty/
https://packagist.org/packages/oliverklee/realty

The extension currently is not compatible with 8.7 yet. There will be a version 2.0.0 soon which will be compatible with TYPO3 CMS 7.6 and 8.7.
